from math import *
print("Enter numbers to perform operation")
n1=int(input("Enter first number")
n2=int(input("Enter second number")
print("Displaying all operation")
print("Addition")
print(n1+n2)
pprint("Subtraction")
print(n1-n2)
rint("Multipplication")
print(n1*n2)
print("Division")
print(n1/n2)
